//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cell_Tool_3.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlockProgram {
            get {
                return ((bool)(this["BlockProgram"]));
            }
            set {
                this["BlockProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte IncorrectPass {
            get {
                return ((byte)(this["IncorrectPass"]));
            }
            set {
                this["IncorrectPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TrialActive {
            get {
                return ((bool)(this["TrialActive"]));
            }
            set {
                this["TrialActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime EndTrialDate {
            get {
                return ((global::System.DateTime)(this["EndTrialDate"]));
            }
            set {
                this["EndTrialDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Admin</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AccList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AccList"]));
            }
            set {
                this["AccList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>123456</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AccPass {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AccPass"]));
            }
            set {
                this["AccPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>y</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DataSourcesPanelVisible {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DataSourcesPanelVisible"]));
            }
            set {
                this["DataSourcesPanelVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>300</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DataSourcesPanelValues {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DataSourcesPanelValues"]));
            }
            set {
                this["DataSourcesPanelValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>y</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection VBoxVisible {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["VBoxVisible"]));
            }
            set {
                this["VBoxVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>y</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TreeViewVisible {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TreeViewVisible"]));
            }
            set {
                this["TreeViewVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>200</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TreeViewSize {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TreeViewSize"]));
            }
            set {
                this["TreeViewSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>@</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TreeViewContent {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TreeViewContent"]));
            }
            set {
                this["TreeViewContent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>@</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OldWorkDir {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OldWorkDir"]));
            }
            set {
                this["OldWorkDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>300</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PropertiesPanelWidth {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PropertiesPanelWidth"]));
            }
            set {
                this["PropertiesPanelWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>y</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PropertiesPanelVisible {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PropertiesPanelVisible"]));
            }
            set {
                this["PropertiesPanelVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>@</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CustomColors {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CustomColors"]));
            }
            set {
                this["CustomColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>200</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BandC {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BandC"]));
            }
            set {
                this["BandC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>130</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Meta {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Meta"]));
            }
            set {
                this["Meta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>y</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BandCVis {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BandCVis"]));
            }
            set {
                this["BandCVis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>y</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MetaVis {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MetaVis"]));
            }
            set {
                this["MetaVis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>y</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SegmentLibPanelVis {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SegmentLibPanelVis"]));
            }
            set {
                this["SegmentLibPanelVis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>y</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SegmentDataPanelVis {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SegmentDataPanelVis"]));
            }
            set {
                this["SegmentDataPanelVis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>y</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SegmentHistPanelVis {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SegmentHistPanelVis"]));
            }
            set {
                this["SegmentHistPanelVis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>200</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SegmentHistPanelHeight {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SegmentHistPanelHeight"]));
            }
            set {
                this["SegmentHistPanelHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>y</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SegmentTreshPanelVis {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SegmentTreshPanelVis"]));
            }
            set {
                this["SegmentTreshPanelVis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>y</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SegmentSpotDetPanelVis {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SegmentSpotDetPanelVis"]));
            }
            set {
                this["SegmentSpotDetPanelVis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>300</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RoiManHeight {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RoiManHeight"]));
            }
            set {
                this["RoiManHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>y</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RoiManVis {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RoiManVis"]));
            }
            set {
                this["RoiManVis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>y</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TrackingVis {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TrackingVis"]));
            }
            set {
                this["TrackingVis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>y</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CTChart_PropertiesVis {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CTChart_PropertiesVis"]));
            }
            set {
                this["CTChart_PropertiesVis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>y</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CTChart_SeriesVis {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CTChart_SeriesVis"]));
            }
            set {
                this["CTChart_SeriesVis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>200</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CTChart_SeriesHeight {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CTChart_SeriesHeight"]));
            }
            set {
                this["CTChart_SeriesHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>@</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CTChart_Functions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CTChart_Functions"]));
            }
            set {
                this["CTChart_Functions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateSettings {
            get {
                return ((bool)(this["UpdateSettings"]));
            }
            set {
                this["UpdateSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>true</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AutoProtocolSettings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AutoProtocolSettings"]));
            }
            set {
                this["AutoProtocolSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>@</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ProtocolSettingsList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProtocolSettingsList"]));
            }
            set {
                this["ProtocolSettingsList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>@</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ResultsExtractorFilters {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ResultsExtractorFilters"]));
            }
            set {
                this["ResultsExtractorFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>@</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SolverFunctions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SolverFunctions"]));
            }
            set {
                this["SolverFunctions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>@</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ResultsExtractorSizes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ResultsExtractorSizes"]));
            }
            set {
                this["ResultsExtractorSizes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>@</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection HotKeys {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["HotKeys"]));
            }
            set {
                this["HotKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>@</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SmartBtns {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SmartBtns"]));
            }
            set {
                this["SmartBtns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowLicense {
            get {
                return ((bool)(this["ShowLicense"]));
            }
            set {
                this["ShowLicense"] = value;
            }
        }
    }
}
